In [2]:
import numpy as np


In [13]:
#create from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [28]:
#create
arr1 = np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape)
arr2 = np.ones((2,3), dtype="int64")
print(arr2, arr2.shape)
arr3 = np.full((3,4), 100)
print(arr3, arr3.shape)
arr4 = np.eye(3,4)
print(arr4, arr4.shape)
arr5 = np.arange(1,11,3)
print(arr5, arr5.shape)
arr6 = np.linspace(1, 100,10)#evenly spaced arrays
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)
[ 1  4  7 10] (4,)
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] (10,)


In [35]:
# properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [42]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [48]:
#indexing
#arr = np.array([1,2,3,4,5,])
arr = np.array([[1,2,3],[4,5,6]])

print(arr[arr >2])
print(arr[arr >3])


[3 4 5 6]
[4 5 6]


In [56]:
arr = np.array([1,2,3,4,5])
#[start, end, step]

print(arr[1:4:2])
print(arr[1:])
print(arr[:4])
print(arr[: :])



[2 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]


In [64]:
# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200
# print(sub_list)
# print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)



[2 3]
[200   3]
[1 2 3 4 5]


In [69]:
arr = np.array([1,2,3.14,4,5, "start"])

print(arr,arr.dtype)

['1' '2' '3.14' '4' '5' 'start'] <U32


In [70]:
arr = np.array([3+5j])
print(arr,arr.dtype)

[3.+5.j] complex128


In [73]:
# multi - dimensional arrays

arr2D = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

45
[12 15 18]
[ 6 15 24]


In [7]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)
print(arr3D[0,1,1])
print(arr3D[:,:,0])
print(arr3D[:,:,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[ 1  3  5]
 [ 7  9 11]]
[[ 1  3  5]
 [ 7  9 11]]


In [9]:
arr = np.array([1,2,3,4,5])

print(arr ** 2)
print(arr + 10)

[ 1  4  9 16 25]
[11 12 13 14 15]


In [11]:
print(arr + 5)


[ 6  7  8  9 10]


In [14]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)

print(arr + arr2)
print(arr.dtype)
print(arr.size)


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
int64
5


In [21]:
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)
norm_array = (arr - mean)/ std_dev
print(norm_array)
print(std_dev)
print(mean)
print(np.sqrt(1.25))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
1.118033988749895
2.5
1.118033988749895


In [28]:
# mathematical fnx

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.log2(arr))

15
120
[0.         1.         1.5849625  2.         2.32192809]


In [31]:
print(np.round(3.56))
print(np.ceil(3.14))
print(np.floor(3.14))

4.0
4.0
3.0
